backend:
  name: github
  repo: snamyorg1/jekyll_blog_posts
  base_url: https://suresh-issue-82.dcycleproject.org
  auth_endpoint: /auth/github/repo/69b6cfce3d9141c0c4f7792a

media_folder: "docs/media"
public_folder: "/media"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
